# Splunk Universal Forwarder on the Windows Server domain controller
# renderXml = 1 sends Security, PowerShell and Sysmon events as XML

[WinEventLog://Application]
index = win_server
disabled = false

[WinEventLog://Security]
index = win_server
disabled = false
renderXml = 1

[WinEventLog://System]
index = win_server
disabled = false

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
index = win_server
disabled = false
renderXml = 1

[WinEventLog://Windows PowerShell]
index = win_server
disabled = false

[WinEventLog://Microsoft-Windows-Windows Defender/Operational]
index = win_server
disabled = false

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = win_server
disabled = false
renderXml = 1
